gimstickets/urls.py
#
# Copyright (c) 2021, Grigoriy Kramarenko <root@rosix.ru>
# All rights reserved.
# This file is distributed under the BSD 3-Clause License.
#
from django.urls import path
from gimstickets.views import index, tickets, ticket

app_name = 'gimstickets'

urlpatterns = [
    path('', index, name='index'),
    path('<int:kit_id>/tickets/', tickets, name='tickets'),
    path('<int:kit_id>/tickets/<int:ticket>/', ticket, name='ticket'),
]

server/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gimstickets.urls', namespace='gimstickets')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gimstickets/models.py
#
# Copyright (c) 2021, Grigoriy Kramarenko <root@rosix.ru>
# All rights reserved.
# This file is distributed under the BSD 3-Clause License.
#
from django.db import models


class Kit(models.Model):
    """
    Модель комплекта экзаменационных билетов.
    """
    id = models.IntegerField(primary_key=True)
    description = models.CharField('описание', max_length=512)
    questions = models.PositiveIntegerField('кол-во вопросов')
    answers = models.PositiveIntegerField('минимум правильных')
    minutes = models.PositiveIntegerField('кол-во минут')
    is_active = models.BooleanField('активен', default=True, db_index=True)

    class Meta:
        ordering = ('id',)
        verbose_name = 'комплект'
        verbose_name_plural = 'комплекты'

    def __str__(self):
        return 'Комплект %d' % self.id


class Question(models.Model):
    """
    Модель вопроса в билете.
    """
    id = models.IntegerField(primary_key=True)
    kit = models.ForeignKey(
        Kit, on_delete=models.CASCADE, verbose_name='комплект')
    ticket = models.PositiveIntegerField('билет', db_index=True)
    number = models.PositiveIntegerField('номер вопроса', db_index=True)
    text = models.CharField('текст вопроса', max_length=512)

    class Meta:
        ordering = ('kit', 'ticket', 'number')
        verbose_name = 'вопрос'
        verbose_name_plural = 'вопросы'

    def __str__(self):
        return self.text

    @property
    def picture(self):
        """Возвращает название файла картинки для этого вороса."""
        return '%d_%d_%d.jpg' % (self.kit_id, self.ticket, self.number)


class Answer(models.Model):
    """
    Модель варианта ответа на вопрос в билете.
    """
    id = models.IntegerField(primary_key=True)
    question = models.ForeignKey(
        Question, on_delete=models.CASCADE, verbose_name='вопрос')
    text = models.CharField('текст ответа', max_length=512)
    is_correct = models.BooleanField('правильный')

    class Meta:
        ordering = ('question', 'text')
        verbose_name = 'ответ'
        verbose_name_plural = 'ответы'

    def __str__(self):
        return self.text

gimstickets/views.py
#
# Copyright (c) 2021, Grigoriy Kramarenko <root@rosix.ru>
# All rights reserved.
# This file is distributed under the BSD 3-Clause License.
#
import logging
from asgiref.sync import sync_to_async

from django.shortcuts import render, get_object_or_404

from gimstickets.models import Kit, Question, Answer

logger = logging.getLogger(__name__)


@sync_to_async
def index(request):
    kits = Kit.objects.filter(is_active=True)
    ctx = {'kits': kits}
    return render(request, 'gimstickets/index.html', ctx)


@sync_to_async
def tickets(request, kit_id):
    kit = get_object_or_404(Kit.objects.filter(is_active=True), id=kit_id)
    qs = Question.objects.filter(kit=kit)
    tickets = qs.order_by('ticket').values_list('ticket', flat=True).distinct()
    ctx = {
        'kit': kit,
        'tickets': tickets,
    }
    return render(request, 'gimstickets/tickets.html', ctx)


@sync_to_async
def ticket(request, kit_id, ticket):
    kit = get_object_or_404(Kit.objects.filter(is_active=True), id=kit_id)
    qs = Answer.objects.filter(question__kit=kit, question__ticket=ticket)
    qs = qs.select_related('question')
    qs = qs.order_by('question__number', 'id')
    ctx = {
        'kit': kit,
        'ticket': ticket,
        'answers': qs,
    }
    qs = Question.objects.filter(kit=kit)
    tickets = qs.order_by('ticket').values_list('ticket', flat=True).distinct()
    if list(tickets)[-1] > ticket:
        ctx['next_ticket'] = ticket + 1
    return render(request, 'gimstickets/ticket.html', ctx)

gimstickets/templates/gimstickets/_navbar.html
{% load navigation %}
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top shadow pt-0 pb-0 d-print-none">
    <div class="container">
        <a class="navbar-brand" href="{% url 'gimstickets:index' %}">Билеты ГИМС</a>
        <span class="navbar-text">учи на диване! 😉</span>
    </div>
</nav>

gimstickets/templates/gimstickets/base.html
{% spaceless %}{% load i18n %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    {% block style_page %}{% endblock %}
    <title>{% block title %}{% trans 'Билеты ГИМС' %}{% endblock %}</title>
</head>
<body class="{% block body_class %}{% endblock %}">
{% block body %}
{% include './_navbar.html' %}
<div class="container mt-5">
{% block container %}
    {% block content %}{% endblock %}
{% endblock %}
</div>
{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment-with-locales.min.js" integrity="sha512-LGXaggshOkD/at6PFNcp2V2unf9LzFq6LE+sChH7ceMTDP0g2kn6Vxwgg7wkPP7AAtX+lmPqPdxB47A0Nz0cMQ==" crossorigin="anonymous"></script>
{% block javascript_page %}{% endblock %}
</body>
</html>
{% endspaceless %}

gimstickets/templates/gimstickets/index.html
{% extends './base.html' %}{% load bootstrap4 html %}

{% block content %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item active" aria-current="page">Комплекты</li>
    </ol>
</nav>

<h1>Выберите комплект билетов.</h1>
<table class="table">
    <tbody>
    {% for kit in kits %}
        <tr>
            <td class="text-nowrap"><a href="{% url 'gimstickets:tickets' kit_id=kit.id %}">{{ kit }}</a></td>
            <td><a href="{% url 'gimstickets:tickets' kit_id=kit.id %}" class="text-body text-decoration-none">{{ kit.description }}</a></td>
        </tr>
    {% endfor%}
    </tbody>
</table>
{% endblock %}

gimstickets/templates/gimstickets/ticket.html
{% extends './base.html' %}{% load static %}

{% block style_page %}
<style type="text/css">
.form-check-label {
    width: 100%;
}

@media print {
    .container {
        width: 100%;
        max-width: 100%;
    }
}
</style>
{% endblock %}

{% block content %}
{% get_static_prefix as STATIC_PREFIX %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'gimstickets:index' %}">Комплекты</a></li>
        <li class="breadcrumb-item"><a href="{% url 'gimstickets:tickets' kit_id=kit.id %}">{{ kit }}</a></li>
        <li class="breadcrumb-item active" aria-current="page">Билет {{ ticket }}</li>
    </ol>
</nav>

<h1>Билет {{ ticket }}</h1>
{% regroup answers by question as question_list %}

<div class="row row-cols-1 row-cols-md-2 g-4 mb-5">
{% for question in question_list %}
    {% with question.grouper.number as number %}
    <div class="col">
        <div class="card h-100">
            <div class="card-body">
                <h5 class="card-title">{{ number }}. {{ question.grouper }}</h5>
                <div class="text-center">
                    <img class="img-fluid" alt="{{ question.grouper.id }}" src="{{ STATIC_PREFIX }}gimstickets/pictures/{{ question.grouper.picture }}">
                </div>
                <div>
                {% for answer in question.list %}
                    <div class="form-check mb-2">
                        <input class="form-check-input {{ answer.is_correct|yesno:'correct,' }}" type="radio" name="question-{{ number }}" id="answer-{{ answer.id }}">
                        <label class="form-check-label pb-3 border-bottom" for="answer-{{ answer.id }}">
                            {{ answer }}
                        </label>
                    </div>
                {% endfor %}
                </div>
                <button class="btn btn-sm btn-outline-secondary mx-3" onclick="answer(this, {{ number }})">показать правильный ответ</button>
            </div>
        </div>
    </div>
    {% endwith %}
{% endfor %}
</div>

{% if next_ticket %}
<div class="text-center mb-5">
    <a href="{% url 'gimstickets:ticket' kit_id=kit.id ticket=next_ticket %}" class="btn btn-secondary btn-lg">Следующий билет >> {{ next_ticket }}</a>
</div>
{% endif %}

{% endblock %}


{% block javascript_page %}
<script>
function answer(button, question) {
    let inputs = document.querySelectorAll('input[name="question-' + question + '"]');
    for (let input of inputs) {
        let label = input.labels[0];
        if (!input.classList.contains('correct')) {
            label.classList.add('text-decoration-line-through');
        }
        if (input.checked) {
            label.classList.add('fw-bold');
            if (input.classList.contains('correct')) {
                label.classList.add('text-success');
            }
            else {
                label.classList.add('text-danger');
            }
        }
        // input.disabled = true;
    }
    button.disabled = true;
}
</script>
{% endblock %}

gimstickets/templates/gimstickets/tickets.html
{% extends './base.html' %}{% load bootstrap4 html %}

{% block content %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'gimstickets:index' %}">Комплекты</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ kit }}</li>
    </ol>
</nav>

<h1>Выберите один из билетов.</h1>
<ul>
{% for ticket in tickets %}
    <li>
        <a href="{% url 'gimstickets:ticket' kit_id=kit.id ticket=ticket %}">Билет {{ ticket }}</a>
    </li>
{% endfor%}
</ul>
{% endblock %}